// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoTYGVDQq20MtjMUHvtLUzpTKme5bRAJY',
    appId: '1:214903872896:web:276581f359d4d1a5653565',
    messagingSenderId: '214903872896',
    projectId: 'flutter-fjpj',
    authDomain: 'flutter-fjpj.firebaseapp.com',
    storageBucket: 'flutter-fjpj.appspot.com',
    measurementId: 'G-Q8N69DDM70',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnG4_avkSZrPqdoGxR21bkkK-p-s4-Ln4',
    appId: '1:214903872896:android:c20b88dcb0ca4080653565',
    messagingSenderId: '214903872896',
    projectId: 'flutter-fjpj',
    storageBucket: 'flutter-fjpj.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC90UbV_dUktCGWg6MeVulcaxFuG5utkEY',
    appId: '1:214903872896:ios:ff7fd706139c3402653565',
    messagingSenderId: '214903872896',
    projectId: 'flutter-fjpj',
    storageBucket: 'flutter-fjpj.appspot.com',
    iosClientId: '214903872896-omk3ip1lidmjeb48jkuqpc9bkthorcn6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC90UbV_dUktCGWg6MeVulcaxFuG5utkEY',
    appId: '1:214903872896:ios:ff7fd706139c3402653565',
    messagingSenderId: '214903872896',
    projectId: 'flutter-fjpj',
    storageBucket: 'flutter-fjpj.appspot.com',
    iosClientId: '214903872896-omk3ip1lidmjeb48jkuqpc9bkthorcn6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterDemo',
  );
}
